### ISSUE TITLE
Org name for publishing artifacts

### ISSUE THREAD

**Issue by sergei-shabanau** [spartanz/agora#2]
@vil1 @GrafBlutwurst @jdegoes 

What would be the organization name for publishing artifacts to sonatype (the `organization` sbt setting) ?

I see the `schemaz` site is using `spartanz.github.io` (https://spartanz.github.io/schemaz/), are we going to use `organization := "io.github.spartanz"` ?

**Comment by vil1** [comment]
I've registered the `spartanz.org` domain name, and opened an `org.spartanz` repository on sonatype

**Comment by sergei-shabanau** [comment]
Awesome! I'll try to use it. Thank you!

**Comment by vil1** [comment]
In order to publish to sonatype, you will need to have the necessary credentials. If you have a sonatype user account, I think I can add you to the `org.spartanz` repository

**Comment by sergei-shabanau** [comment]
@vil1 Yes, I have sonatype account, do you need username and password?

**Comment by sergei-shabanau** [comment]
@vil1 
Everything works! Thanks a lot!

![image](https://user-images.githubusercontent.com/12940501/61456946-4bb49f00-a935-11e9-8653-0201b820053b.png)
